# Generated by Django 2.2.2 on 2019-06-28 21:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number_of_pages', models.CharField(max_length=255)),
                ('release_date', models.DateTimeField()),
                ('isbn', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
