# Generated by Django 2.2.2 on 2019-06-29 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0002_auto_20190629_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='deleted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
