version: "3"
services:
  app:
    build: . # Current directory!
    command: "python3 my_apps/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "33306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_DATABASE=lib
      - MYSQL_USER=lib
      - MYSQL_PASSWORD=123

volumes:
  postgres_data:
